Rails.application.routes.draw do
  get 'credit_cards/index'
  get 'credit_cards/show'
  get 'credit_cards/create'
  get 'credit_cards/edit'
  get 'credit_cards/destroy'
  get 'credit_cards/update'
  get 'credit_cards/new'
  get 'users/index'
  get 'users/show'
  get 'users/create'
  get 'users/edit'
  get 'users/destroy'
  get 'users/update'
  get 'users/new'
  get 'items/index'
  get 'items/show'
  get 'items/create'
  get 'items/edit'
  get 'items/destroy'
  get 'items/update'
  get 'items/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
